### ISSUE TITLE
error getdata if use 2 component 

### ISSUE THREAD

**Issue by trinhquyswe** [StylishEsper/ESave#2]
I discovered an error, if 2 components use a file save , in runtime this component calls AddOrUpdate, and then the other component GetData, it will get the file saved before AddOrUpdate of the other component, or the file saved before runtime, if I only use 1 component to get data. After addorupdate it doesn't error

**Comment by EsperGames** [comment]
I'm not sure why you need two GameObjects with the SaveFileSetup component. But yes, the data may not be identical because the data that's stored in memory by the SaveFile class isn't exactly the same as the data in the target file until the SaveFile.Save method is called. The Save method officially writes the data into the target file.

Even then, you would need to call the Load method on the other SaveFile class for it to get the updated data from the file. The SaveFileSetup component is meant to be used once for each save file. If you only have one file to target, I don't see a reason to use the component on two different GameObjects.

Is there a reason why you can't create a public static field for a SaveFile?

```
public class Save : MonoBehaviour
{
    public static SaveFile saveFile;

    private void Start()
    {
        saveFile = GetComponent<SaveFileSetup>().saveFile;
    }
}
```
And then you can access this anywhere as below:

```
Save.saveFile
```

Let me know if this has helped.

**Comment by QuyGDb** [comment]
Thanks, it helps me a lot <3

**Comment by trinhquyswe** [comment]
I can solve the problem by  1 component but I noticed a strange behavior when using 2 components, I don't know if it's a bug or not. It's hard to explain in words, can I send a video : https://www.youtube.com/watch?v=y4cXcSnQ_6w

**Comment by EsperGames** [comment]
Thanks for taking the time to make a video.

This doesn't seem to be a bug. The SaveFileSetup component gets the file data and stores it into memory on awake. Your GameManager is saving the data on start, which occurs after awake. So, the EnemyManager component is using the data from the save file before the GameManager updates its data.

Even if you were to make it save on awake, you would have to see which awake method is running first. You can change a script's execution order with the DefaultExecutionOrder attribute.

https://docs.unity3d.com/ScriptReference/DefaultExecutionOrder.html

SaveFile's Load method updates the data in memory. But it's best to just have one SaveFileSetup component for a single save file so that there's no data discrepancies.

**Comment by trinhquyswe** [comment]
now i understand, the keyword here is SaveFileSetup component takes file data and saves it in memory while awake, tks u
